"use client";

import { useEffect } from "react";
import { motion } from "framer-motion";
import {
  BookOpen,
  ArrowRight,
  ShieldCheck,
  Eye,
  RefreshCw,
} from "lucide-react";
import Link from "next/link";

const EASE = [0.16, 1, 0.3, 1] as const;
const MONO_STACK =
  'var(--font-jetbrains-mono), ui-monospace, "SF Mono", Menlo, Monaco, monospace';

const fadeUp = {
  initial: { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.7, ease: EASE },
};

export default function ThesisPage() {
  useEffect(() => {
    document.title =
      "The Scrutexity Thesis — Governing Clinical Demand in the AI Era";
    const meta = document.querySelector('meta[name="description"]');
    if (meta) {
      meta.setAttribute(
        "content",
        "Generative AI changed how patients discover medical aesthetics. Scrutexity was engineered as a governance ledger—a definitive system to prove what's true and protect patient trust."
      );
    }
  }, []);

  return (
    <main className="min-h-screen bg-cream text-espresso font-sans antialiased pt-[100px]">

      {/* ═══ TITLE SECTION ═══ */}
      <section className="bg-cream-deep px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-4xl text-center">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: EASE }}
          >
            <span
              className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-sage-deep"
              style={{ fontFamily: MONO_STACK }}
            >
              <BookOpen className="h-3.5 w-3.5" />
              Thesis · Systems Architecture
            </span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: EASE, delay: 0.1 }}
            className="mt-8 font-display text-4xl leading-tight tracking-tight text-espresso sm:text-5xl md:text-6xl"
          >
            The Scrutexity Thesis:{" "}
            <span className="italic text-sage-deep">
              Governing Clinical Demand in the AI Era
            </span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: EASE, delay: 0.15 }}
            className="mt-6 font-display text-xl italic tracking-tight text-clay md:text-2xl"
          >
            By Nick Altstein, Systems Architect
          </motion.p>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: EASE, delay: 0.2 }}
            className="mx-auto mt-8 max-w-3xl text-base leading-8 text-mist md:text-lg"
          >
            Generative AI fundamentally changed how patients discover medical
            aesthetics, but the industry&rsquo;s infrastructure did not adapt. We
            watched high-trust practices publish clinical claims that AI models
            would hallucinate and regulators would flag. Scrutexity was not built
            as a marketing tool. It was engineered as a governance ledger&mdash;a
            definitive system to prove what is true, protect patient trust, and
            automatically recover the demand generated by that trust.
          </motion.p>
        </div>
      </section>

      {/* ═══ PART I: THE DIAGNOSIS OF UNSEEN RISK ═══ */}
      <section className="bg-cream px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-4xl">
          <motion.div {...fadeUp} className="flex items-start gap-6">
            <div className="hidden shrink-0 sm:block">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-sage/25 bg-sage/10 text-sage-deep">
                <Eye className="h-5 w-5" />
              </div>
            </div>
            <div>
              <span
                className="inline-block text-xs font-semibold uppercase tracking-[0.12em] text-sage-deep"
                style={{ fontFamily: MONO_STACK }}
              >
                Part I
              </span>
              <h2 className="mt-2 font-display text-3xl leading-tight tracking-tight text-espresso md:text-4xl">
                Part I — The Diagnosis of Unseen Risk
              </h2>
              <p className="mt-6 text-base leading-8 text-mist md:text-lg">
                Digital visibility used to rely on simple indexing. Generative
                AI severed that relationship — search engines became synthesis
                engines. When a clinic&rsquo;s digital footprint lacks
                governance, AI models guess, hallucinate credentials,
                misattribute outcomes, and introduce &ldquo;Claim Drift.&rdquo;
                For a medical operator, this is not a marketing problem — it is a
                severe regulatory liability.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ═══ PART II: THE FAILURE OF TRADITIONAL MARKETING ═══ */}
      <section className="bg-cream-deep px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-4xl">
          <motion.div {...fadeUp} className="flex items-start gap-6">
            <div className="hidden shrink-0 sm:block">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-clay/20 bg-clay/10 text-clay">
                <RefreshCw className="h-5 w-5" />
              </div>
            </div>
            <div>
              <span
                className="inline-block text-xs font-semibold uppercase tracking-[0.12em] text-sage-deep"
                style={{ fontFamily: MONO_STACK }}
              >
                Part II
              </span>
              <h2 className="mt-2 font-display text-3xl leading-tight tracking-tight text-espresso md:text-4xl">
                Part II — The Failure of Traditional Marketing
              </h2>
              <p className="mt-6 text-base leading-8 text-mist md:text-lg">
                Traditional agencies try to manipulate the models, prioritizing
                volume over verifiable truth. This fails because it ignores the
                fundamental requirement of clinical operations: Governance.
                Generating traffic without a standardized record of truth
                accelerates Claim Drift and fails to close the loop on patient
                inquiries.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ═══ PART III: THE INFRASTRUCTURE SOLUTION ═══ */}
      <section className="bg-cream px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-4xl">
          <motion.div {...fadeUp} className="flex items-start gap-6">
            <div className="hidden shrink-0 sm:block">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-sage/25 bg-sage/10 text-sage-deep">
                <ShieldCheck className="h-5 w-5" />
              </div>
            </div>
            <div>
              <span
                className="inline-block text-xs font-semibold uppercase tracking-[0.12em] text-sage-deep"
                style={{ fontFamily: MONO_STACK }}
              >
                Part III
              </span>
              <h2 className="mt-2 font-display text-3xl leading-tight tracking-tight text-espresso md:text-4xl">
                Part III — The Infrastructure Solution
              </h2>
              <p className="mt-6 text-base leading-8 text-mist md:text-lg">
                We abandoned the concept of &ldquo;SEO&rdquo; for strict,
                verifiable infrastructure. Scrutexity is the AI Visibility
                Scanner — an operating system to establish Entity Truth. By
                transforming raw clinical outcomes into structured,
                machine-readable artifacts, we force AI models to cite the
                practice accurately. Every claim is anchored by a cryptographic
                ledger.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ═══ PART IV: REVENUE RECOVERY ═══ */}
      <section className="bg-cream-deep px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-4xl">
          <motion.div {...fadeUp} className="flex items-start gap-6">
            <div className="hidden shrink-0 sm:block">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-clay/20 bg-clay/10 text-clay">
                <RefreshCw className="h-5 w-5" />
              </div>
            </div>
            <div>
              <span
                className="inline-block text-xs font-semibold uppercase tracking-[0.12em] text-sage-deep"
                style={{ fontFamily: MONO_STACK }}
              >
                Part IV
              </span>
              <h2 className="mt-2 font-display text-3xl leading-tight tracking-tight text-espresso md:text-4xl">
                Part IV — Revenue Recovery and Operational Reality
              </h2>
              <p className="mt-6 text-base leading-8 text-mist md:text-lg">
                Governing visibility is only half the equation. When clinical
                truth aligns with digital visibility, inquiries increase. Manual
                front-desk operations inevitably drop some. Scrutexity&rsquo;s
                Revenue Recovery layer uses read-only telemetry to identify
                unconverted inquiries and unbooked consultations — recovering
                demand without disrupting workflows.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ═══ CTA SECTION ═══ */}
      <section className="bg-cream px-5 py-20 sm:px-8 lg:py-28">
        <div className="mx-auto max-w-2xl text-center">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, ease: EASE }}
            className="font-display text-3xl tracking-tight text-espresso md:text-4xl"
          >
            Ready to govern your clinical demand.
          </motion.h2>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, ease: EASE, delay: 0.1 }}
            className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
          >
            <Link
              href="https://auditgpt.ai/snapshot"
              className="clay-cta inline-flex items-center gap-2 rounded-xl bg-clay px-7 py-4 text-sm font-semibold text-cream transition-all duration-300 hover:bg-clay-deep"
            >
              Read the full claim intelligence brief →
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/safety-architecture"
              className="inline-flex items-center gap-2 rounded-xl border border-sand-deep/30 bg-cream-deep px-7 py-4 text-sm font-semibold text-espresso transition-all duration-300 hover:bg-sand-deep/20"
            >
              Explore the infrastructure →
              <ArrowRight className="h-4 w-4" />
            </Link>
          </motion.div>

          <motion.p
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, ease: EASE, delay: 0.2 }}
            className="mx-auto mt-8 max-w-lg text-xs leading-5 text-mist/60"
            style={{ fontFamily: MONO_STACK }}
          >
            Boundary: This thesis describes the architectural rationale and
            operational design of Scrutexity. It does not constitute legal
            advice, regulatory clearance, or FDA approval. Consult your
            compliance counsel before making material changes to your clinical
            marketing infrastructure.
          </motion.p>
        </div>
      </section>

    </main>
  );
}
