"use client";
import { CheckCircle2, Loader2, Send } from "lucide-react";
import { useRef,useState,type FormEvent } from "react";

export default function ContactIntakeForm({source="construction-contact"}:{initialOffer?:string;source?:string}){
  const idempotencyKey=useRef(crypto.randomUUID()); const [state,setState]=useState<"idle"|"submitting"|"saved"|"error">("idle"); const [message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("submitting");setMessage("");const f=new FormData(event.currentTarget);try{const res=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey.current},body:JSON.stringify({name:f.get("name"),email:f.get("email"),websiteUrl:f.get("websiteUrl")||"",company:f.get("company"),role:f.get("role"),context:f.get("context"),companyWebsite:f.get("companyWebsite"),offer:"construction-diagnostic",source,consent:f.get("consent")==="on"})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"Unable to save your request.");setState("saved");setMessage("Your diagnostic request is saved. Nick will follow up to confirm project fit, scope, and a secure exchange path.")}catch(e){setState("error");setMessage(e instanceof Error?e.message:"Unable to save your request.")}}
  if(state==="saved")return <div className="rounded-3xl bg-white p-8 shadow-[var(--sx-shadow)]" role="status"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sx-accent"><CheckCircle2 size={22}/></span><h2 className="sx-h3 mt-7">Request received.</h2><p className="mt-4 text-sm leading-6 text-sx-muted">{message}</p></div>;
  const field="mt-2 min-h-12 w-full rounded-xl border border-sx-border bg-sx-surface-muted px-4 py-3 text-sm outline-none transition focus:border-sx-ink focus:ring-2 focus:ring-sx-accent";
  return <form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-[var(--sx-shadow)] sm:p-9"><p className="sx-mono text-sx-muted">Diagnostic intake</p><h2 className="sx-h3 mt-4">Tell us about the work.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Name<input className={field} name="name" autoComplete="name" required minLength={2}/></label><label className="text-sm font-medium">Work email<input className={field} name="email" type="email" autoComplete="email" required/></label><label className="text-sm font-medium">Company<input className={field} name="company" autoComplete="organization" required/></label><label className="text-sm font-medium">Role<input className={field} name="role" autoComplete="organization-title" required/></label></div><label className="mt-5 block text-sm font-medium">Company website <span className="font-normal text-sx-muted">(optional)</span><input className={field} name="websiteUrl" type="url" placeholder="https://company.com"/></label><label className="mt-5 block text-sm font-medium">Active project and upcoming crew decision<textarea className={field} name="context" rows={5} maxLength={2000} placeholder="Trade, project type, workfronts, and the deployment decision you need to make." required/></label><label className="sr-only" aria-hidden="true">Company website confirmation<input name="companyWebsite" tabIndex={-1} autoComplete="off"/></label><label className="mt-6 flex items-start gap-3 text-xs leading-5 text-sx-muted"><input className="mt-1 h-4 w-4 accent-[#35363b]" name="consent" type="checkbox" required/><span>I agree that Scrutexity may use these details to respond. I will not submit confidential, personal, safety-critical, or regulated data through this form.</span></label>{state==="error"&&<p className="mt-4 text-sm text-red-700" role="alert">{message}</p>}<button type="submit" disabled={state==="submitting"} className="sx-button sx-button-primary mt-7 w-full disabled:cursor-wait disabled:opacity-65"><span className="sx-button-icon">{state==="submitting"?<Loader2 size={17} className="animate-spin"/>:<Send size={17}/>}</span>{state==="submitting"?"Saving request…":"Request the 5-Day Diagnostic"}</button><p className="mt-4 text-center text-[11px] leading-5 text-sx-muted">No payment is taken through this form.</p></form>
}
