import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export const metadata: Metadata = { title: "About Scrutexity | Contractor-Side Production Control", description: "Scrutexity preserves the lineage between planned starts, observed field evidence, contractor decisions, and actual execution.", alternates: { canonical: "/about" } };
const standards = [["OBSERVE BEFORE OUTCOME", "Capture the available field state before the result is known."], ["SEPARATE THE STATES", "Intent, observation, decision, and actual execution remain distinct."], ["RETAIN THE SOURCE", "Evidence keeps its timestamp, context, and relation to the workfront."], ["KEEP AUTHORITY HUMAN", "The contractor retains the operational decision."]] as const;

export default function AboutPage() {
  return <div className="min-h-screen bg-sx-bg pb-28 pt-32"><section className="sx-container"><p className="sx-eyebrow">ABOUT SCRUTEXITY</p><h1 className="sx-display mt-7 max-w-[1050px]">Construction decisions deserve a record of what was knowable.</h1><div className="mt-14 grid gap-10 border-t border-sx-border pt-10 lg:grid-cols-[.75fr_1.25fr]"><p className="sx-mono text-sx-muted">WHY WE EXIST</p><div className="max-w-[720px] space-y-6 text-lg leading-8 text-sx-muted"><p>The schedule records where work is intended to happen. The field produces changing evidence about the conditions surrounding that work. Specialty contractors still have to decide where to send the crew.</p><p>Scrutexity exists to preserve the lineage between those states: planned start, observed evidence, contractor decision, subsequent actual execution, and sealed record.</p><p>It is contractor-side production control—not a readiness certification and not an autonomous go/no-go system.</p></div></div></section><section className="sx-section"><div className="sx-container"><p className="sx-eyebrow">OPERATING STANDARD</p><h2 className="sx-h2 max-w-[760px]">Record carefully. Claim only what the evidence supports.</h2><div className="sx-trade-grid">{standards.map(([title, copy], index) => <article key={title}><p className="sx-mono text-sx-muted">0{index + 1}</p><h3>{title}</h3><p className="mt-5 max-w-md text-sm leading-6 text-sx-muted">{copy}</p></article>)}</div></div></section><section className="sx-container border-t border-sx-border py-24 text-center"><p className="sx-eyebrow">ONE ACTIVE WORKFRONT</p><h2 className="sx-h2">Start with the 5-Day Diagnostic.</h2><p className="sx-body mx-auto mt-6 max-w-[620px]">See how planned deployment, available field evidence, contractor decision, and actual execution assemble into a controlled record.</p><Link href="/contact?intent=construction-diagnostic&source=about" className="sx-button sx-button-primary mt-8"><ArrowRight size={17}/>Request Diagnostic</Link></section></div>;
}
